/**
 * 跟读场景 + 多语言词汇种子（考试常见场景）。
 * 幂等：按 category.code / (categoryId, languageId, word) 去重。
 */
import type { AppPrismaClient } from "./prisma";

export const READ_ALOUD_SEED_TAG = "seed_read_aloud_v1";

type LocaleName = { name: string; description: string };
type VocabItem = { word: string; example: string };

const CATEGORIES = [
  {
    code: "shopping",
    name: "购物",
    nameEn: "Shopping",
    icon: "shopping_bag_outlined",
    description: "商场、超市、服装店等购物常用表达",
    descriptionEn: "Shopping at malls, markets, and clothing stores",
    sortOrder: 10,
    locales: {
      en: { name: "Shopping", description: "Useful phrases for shopping" },
      zh: { name: "购物", description: "商场、超市、服装店等购物常用表达" },
      ja: { name: "買い物", description: "買い物でよく使う表現" },
      es: { name: "Compras", description: "Expresiones útiles para ir de compras" },
      fr: { name: "Shopping", description: "Expressions utiles pour faire les courses" },
      de: { name: "Einkaufen", description: "Nützliche Ausdrücke beim Einkaufen" },
    } satisfies Record<string, LocaleName>,
  },
  {
    code: "travel",
    name: "旅游",
    nameEn: "Travel",
    icon: "flight_takeoff",
    description: "问路、交通、景点等旅游场景",
    descriptionEn: "Directions, transport, and sightseeing",
    sortOrder: 20,
    locales: {
      en: { name: "Travel", description: "Directions, transport, and sightseeing" },
      zh: { name: "旅游", description: "问路、交通、景点等旅游场景" },
      ja: { name: "旅行", description: "道案内・交通・観光の表現" },
      es: { name: "Viajes", description: "Direcciones, transporte y turismo" },
      fr: { name: "Voyage", description: "Itinéraire, transport et tourisme" },
      de: { name: "Reisen", description: "Wege, Verkehr und Sightseeing" },
    } satisfies Record<string, LocaleName>,
  },
  {
    code: "hotel",
    name: "酒店",
    nameEn: "Hotel",
    icon: "hotel_outlined",
    description: "入住、退房、客房服务等酒店表达",
    descriptionEn: "Check-in, check-out, and room service",
    sortOrder: 30,
    locales: {
      en: { name: "Hotel", description: "Check-in, check-out, and room service" },
      zh: { name: "酒店", description: "入住、退房、客房服务等酒店表达" },
      ja: { name: "ホテル", description: "チェックイン・チェックアウト・客室サービス" },
      es: { name: "Hotel", description: "Check-in, check-out y servicio de habitación" },
      fr: { name: "Hôtel", description: "Arrivée, départ et service en chambre" },
      de: { name: "Hotel", description: "Check-in, Check-out und Zimmerservice" },
    } satisfies Record<string, LocaleName>,
  },
  {
    code: "restaurant",
    name: "餐厅",
    nameEn: "Restaurant",
    icon: "restaurant_outlined",
    description: "点餐、订位、结账等餐厅表达",
    descriptionEn: "Ordering, reservations, and paying the bill",
    sortOrder: 40,
    locales: {
      en: { name: "Restaurant", description: "Ordering, reservations, and paying the bill" },
      zh: { name: "餐厅", description: "点餐、订位、结账等餐厅表达" },
      ja: { name: "レストラン", description: "注文・予約・会計の表現" },
      es: { name: "Restaurante", description: "Pedir, reservar y pagar la cuenta" },
      fr: { name: "Restaurant", description: "Commander, réserver et régler l'addition" },
      de: { name: "Restaurant", description: "Bestellen, reservieren und bezahlen" },
    } satisfies Record<string, LocaleName>,
  },
  {
    code: "airport",
    name: "机场",
    nameEn: "Airport",
    icon: "local_airport",
    description: "值机、安检、登机等机场常用表达",
    descriptionEn: "Check-in, security, and boarding",
    sortOrder: 50,
    locales: {
      en: { name: "Airport", description: "Check-in, security, and boarding" },
      zh: { name: "机场", description: "值机、安检、登机等机场常用表达" },
      ja: { name: "空港", description: "チェックイン・保安検査・搭乗の表現" },
      es: { name: "Aeropuerto", description: "Facturación, seguridad y embarque" },
      fr: { name: "Aéroport", description: "Enregistrement, sécurité et embarquement" },
      de: { name: "Flughafen", description: "Check-in, Sicherheit und Boarding" },
    } satisfies Record<string, LocaleName>,
  },
] as const;

/** 每场景 × 语言 20 个考试常见词汇与例句 */
export const VOCAB_BY_CATEGORY: Record<string, Record<string, VocabItem[]>> = {
  shopping: {
    en: [
      { word: "receipt", example: "Could I have a receipt, please?" },
      { word: "discount", example: "Is there a discount on this jacket?" },
      { word: "size", example: "Do you have this in a larger size?" },
      { word: "fitting room", example: "Where is the fitting room?" },
      { word: "cash register", example: "Please pay at the cash register." },
      { word: "price tag", example: "I can't find the price tag." },
      { word: "refund", example: "I'd like a refund for this item." },
      { word: "exchange", example: "Can I exchange this for another color?" },
      { word: "bargain", example: "This is a real bargain today." },
      { word: "shopping cart", example: "I left my shopping cart near the entrance." },
      { word: "checkout", example: "The checkout line is too long." },
      { word: "on sale", example: "These shoes are on sale this week." },
      { word: "out of stock", example: "Sorry, that color is out of stock." },
      { word: "customer service", example: "Please go to customer service for help." },
      { word: "credit card", example: "Do you accept credit cards?" },
      { word: "loyalty card", example: "Do you have a loyalty card?" },
      { word: "try on", example: "May I try this on?" },
      { word: "aisle", example: "Milk is in aisle five." },
      { word: "warranty", example: "Does this come with a warranty?" },
      { word: "gift wrap", example: "Could you gift wrap this for me?" },
    ],
    zh: [
      { word: "收据", example: "请给我一张收据。" },
      { word: "折扣", example: "这件外套有折扣吗？" },
      { word: "尺码", example: "有更大的尺码吗？" },
      { word: "试衣间", example: "试衣间在哪里？" },
      { word: "收银台", example: "请到收银台付款。" },
      { word: "价签", example: "我找不到价签。" },
      { word: "退款", example: "我想退这件商品。" },
      { word: "换货", example: "可以换成别的颜色吗？" },
      { word: "便宜货", example: "今天这真是个便宜货。" },
      { word: "购物车", example: "我把购物车放在入口附近了。" },
      { word: "结账", example: "结账队伍太长了。" },
      { word: "特价", example: "这双鞋本周特价。" },
      { word: "缺货", example: "抱歉，那个颜色缺货了。" },
      { word: "客服", example: "请去客服台求助。" },
      { word: "信用卡", example: "你们接受信用卡吗？" },
      { word: "会员卡", example: "您有会员卡吗？" },
      { word: "试穿", example: "我可以试穿这件吗？" },
      { word: "货架通道", example: "牛奶在第五通道。" },
      { word: "保修", example: "这个有保修吗？" },
      { word: "礼品包装", example: "能帮我做礼品包装吗？" },
    ],
    ja: [
      { word: "レシート", example: "レシートをいただけますか。" },
      { word: "割引", example: "このジャケットは割引がありますか。" },
      { word: "サイズ", example: "もう少し大きいサイズはありますか。" },
      { word: "試着室", example: "試着室はどこですか。" },
      { word: "レジ", example: "レジでお支払いください。" },
      { word: "値札", example: "値札が見つかりません。" },
      { word: "返金", example: "この商品を返金したいです。" },
      { word: "交換", example: "別の色に交換できますか。" },
      { word: "お買い得", example: "これは本当にお買い得です。" },
      { word: "カート", example: "カートを入口の近くに置きました。" },
      { word: "会計", example: "会計の列が長すぎます。" },
      { word: "セール", example: "この靴は今週セールです。" },
      { word: "在庫切れ", example: "すみません、その色は在庫切れです。" },
      { word: "カスタマーサービス", example: "カスタマーサービスへお越しください。" },
      { word: "クレジットカード", example: "クレジットカードは使えますか。" },
      { word: "ポイントカード", example: "ポイントカードはお持ちですか。" },
      { word: "試着する", example: "これを試着してもいいですか。" },
      { word: "通路", example: "牛乳は五番の通路にあります。" },
      { word: "保証", example: "これは保証付きですか。" },
      { word: "ギフト包装", example: "ギフト包装をお願いできますか。" },
    ],
    es: [
      { word: "recibo", example: "¿Me puede dar un recibo, por favor?" },
      { word: "descuento", example: "¿Hay descuento en esta chaqueta?" },
      { word: "talla", example: "¿Tiene esto en una talla más grande?" },
      { word: "probador", example: "¿Dónde está el probador?" },
      { word: "caja", example: "Pague en la caja, por favor." },
      { word: "etiqueta de precio", example: "No encuentro la etiqueta de precio." },
      { word: "reembolso", example: "Quiero un reembolso de este artículo." },
      { word: "cambio", example: "¿Puedo cambiarlo por otro color?" },
      { word: "ganga", example: "Esto es una verdadera ganga hoy." },
      { word: "carrito", example: "Dejé el carrito cerca de la entrada." },
      { word: "pago", example: "La fila para pagar es muy larga." },
      { word: "en oferta", example: "Estos zapatos están en oferta esta semana." },
      { word: "agotado", example: "Lo siento, ese color está agotado." },
      { word: "atención al cliente", example: "Vaya a atención al cliente para ayuda." },
      { word: "tarjeta de crédito", example: "¿Aceptan tarjetas de crédito?" },
      { word: "tarjeta de fidelidad", example: "¿Tiene una tarjeta de fidelidad?" },
      { word: "probarse", example: "¿Puedo probármelo?" },
      { word: "pasillo", example: "La leche está en el pasillo cinco." },
      { word: "garantía", example: "¿Esto incluye garantía?" },
      { word: "envolver para regalo", example: "¿Puede envolverlo para regalo?" },
    ],
    fr: [
      { word: "reçu", example: "Pourrais-je avoir un reçu, s'il vous plaît ?" },
      { word: "remise", example: "Y a-t-il une remise sur cette veste ?" },
      { word: "taille", example: "Avez-vous ceci en plus grande taille ?" },
      { word: "cabine d'essayage", example: "Où est la cabine d'essayage ?" },
      { word: "caisse", example: "Veuillez payer à la caisse." },
      { word: "étiquette de prix", example: "Je ne trouve pas l'étiquette de prix." },
      { word: "remboursement", example: "Je voudrais un remboursement pour cet article." },
      { word: "échanger", example: "Puis-je l'échanger contre une autre couleur ?" },
      { word: "bonne affaire", example: "C'est vraiment une bonne affaire aujourd'hui." },
      { word: "caddie", example: "J'ai laissé mon caddie près de l'entrée." },
      { word: "passer en caisse", example: "La file pour passer en caisse est trop longue." },
      { word: "en solde", example: "Ces chaussures sont en solde cette semaine." },
      { word: "en rupture de stock", example: "Désolé, cette couleur est en rupture de stock." },
      { word: "service client", example: "Veuillez vous adresser au service client." },
      { word: "carte de crédit", example: "Acceptez-vous les cartes de crédit ?" },
      { word: "carte de fidélité", example: "Avez-vous une carte de fidélité ?" },
      { word: "essayer", example: "Puis-je essayer ceci ?" },
      { word: "allée", example: "Le lait est dans l'allée cinq." },
      { word: "garantie", example: "Est-ce que cela vient avec une garantie ?" },
      { word: "emballage cadeau", example: "Pouvez-vous faire un emballage cadeau ?" },
    ],
    de: [
      { word: "Quittung", example: "Könnte ich bitte eine Quittung haben?" },
      { word: "Rabatt", example: "Gibt es einen Rabatt auf diese Jacke?" },
      { word: "Größe", example: "Haben Sie das in einer größeren Größe?" },
      { word: "Umkleidekabine", example: "Wo ist die Umkleidekabine?" },
      { word: "Kasse", example: "Bitte zahlen Sie an der Kasse." },
      { word: "Preisschild", example: "Ich finde das Preisschild nicht." },
      { word: "Rückerstattung", example: "Ich möchte eine Rückerstattung für diesen Artikel." },
      { word: "umtauschen", example: "Kann ich das gegen eine andere Farbe umtauschen?" },
      { word: "Schnäppchen", example: "Das ist heute ein echtes Schnäppchen." },
      { word: "Einkaufswagen", example: "Ich habe den Einkaufswagen am Eingang gelassen." },
      { word: "zur Kasse gehen", example: "Die Schlange an der Kasse ist zu lang." },
      { word: "im Angebot", example: "Diese Schuhe sind diese Woche im Angebot." },
      { word: "ausverkauft", example: "Leider ist diese Farbe ausverkauft." },
      { word: "Kundenservice", example: "Bitte gehen Sie zum Kundenservice." },
      { word: "Kreditkarte", example: "Akzeptieren Sie Kreditkarten?" },
      { word: "Kundenkarte", example: "Haben Sie eine Kundenkarte?" },
      { word: "anprobieren", example: "Darf ich das anprobieren?" },
      { word: "Gang", example: "Milch ist im fünften Gang." },
      { word: "Garantie", example: "Gibt es dafür eine Garantie?" },
      { word: "Geschenkverpackung", example: "Können Sie das als Geschenk verpacken?" },
    ],
  },
  travel: {
    en: [
      { word: "tourist attraction", example: "Which tourist attraction should I visit first?" },
      { word: "map", example: "Could you show me on the map?" },
      { word: "subway", example: "How do I get to the subway station?" },
      { word: "bus stop", example: "Is this the right bus stop for downtown?" },
      { word: "ticket", example: "Where can I buy a ticket?" },
      { word: "guidebook", example: "I left my guidebook at the hotel." },
      { word: "souvenir", example: "I'd like to buy a small souvenir." },
      { word: "itinerary", example: "Let me check my itinerary for tomorrow." },
      { word: "landmark", example: "That tower is a famous landmark." },
      { word: "directions", example: "Can you give me directions to the museum?" },
      { word: "luggage", example: "My luggage is too heavy." },
      { word: "passport", example: "Don't forget your passport." },
      { word: "currency exchange", example: "Where is the nearest currency exchange?" },
      { word: "taxi stand", example: "The taxi stand is outside the station." },
      { word: "timetable", example: "Could I see the train timetable?" },
      { word: "sightseeing", example: "We spent the day sightseeing." },
      { word: "local specialty", example: "What is the local specialty here?" },
      { word: "lost and found", example: "I need to go to lost and found." },
      { word: " Pedestrian street", example: "The old town has a nice pedestrian street." },
      { word: "photo spot", example: "This is a popular photo spot." },
    ],
    zh: [
      { word: "旅游景点", example: "我应该先去哪个旅游景点？" },
      { word: "地图", example: "能在地图上指给我看吗？" },
      { word: "地铁", example: "去地铁站怎么走？" },
      { word: "公交站", example: "去市中心是在这个公交站吗？" },
      { word: "票", example: "在哪里可以买票？" },
      { word: "旅游手册", example: "我把旅游手册忘在酒店了。" },
      { word: "纪念品", example: "我想买个小纪念品。" },
      { word: "行程", example: "我看看明天的行程。" },
      { word: "地标", example: "那座塔是著名地标。" },
      { word: "路线", example: "能告诉我去博物馆的路线吗？" },
      { word: "行李", example: "我的行李太重了。" },
      { word: "护照", example: "别忘了带护照。" },
      { word: "货币兑换", example: "最近的货币兑换处在哪里？" },
      { word: "出租车站", example: "出租车站在车站外面。" },
      { word: "时刻表", example: "能看一下火车时刻表吗？" },
      { word: "观光", example: "我们花了一天时间观光。" },
      { word: "当地特色", example: "这里的当地特色是什么？" },
      { word: "失物招领", example: "我需要去失物招领处。" },
      { word: "步行街", example: "老城区有一条很好的步行街。" },
      { word: "拍照点", example: "这是一个热门拍照点。" },
    ],
    ja: [
      { word: "観光地", example: "最初にどの観光地を訪れるべきですか。" },
      { word: "地図", example: "地図で教えていただけますか。" },
      { word: "地下鉄", example: "地下鉄の駅へはどう行けばいいですか。" },
      { word: "バス停", example: "都心行きはこのバス停で合っていますか。" },
      { word: "切符", example: "切符はどこで買えますか。" },
      { word: "ガイドブック", example: "ガイドブックをホテルに置き忘れました。" },
      { word: "お土産", example: "小さなお土産を買いたいです。" },
      { word: "旅程", example: "明日の旅程を確認します。" },
      { word: "名所", example: "あの塔は有名な名所です。" },
      { word: "道順", example: "博物館への道順を教えてください。" },
      { word: "荷物", example: "荷物が重すぎます。" },
      { word: "パスポート", example: "パスポートを忘れないでください。" },
      { word: "両替所", example: "一番近い両替所はどこですか。" },
      { word: "タクシー乗り場", example: "タクシー乗り場は駅の外です。" },
      { word: "時刻表", example: "列車の時刻表を見せていただけますか。" },
      { word: "観光", example: "一日中観光しました。" },
      { word: "名物", example: "ここの名物は何ですか。" },
      { word: "遺失物取扱所", example: "遺失物取扱所に行く必要があります。" },
      { word: "歩行者天国", example: "旧市街には素敵な歩行者天国があります。" },
      { word: "撮影スポット", example: "ここは人気の撮影スポットです。" },
    ],
    es: [
      { word: "atracción turística", example: "¿Qué atracción turística debo visitar primero?" },
      { word: "mapa", example: "¿Puede mostrármelo en el mapa?" },
      { word: "metro", example: "¿Cómo llego a la estación de metro?" },
      { word: "parada de autobús", example: "¿Es esta la parada correcta para el centro?" },
      { word: "boleto", example: "¿Dónde puedo comprar un boleto?" },
      { word: "guía turística", example: "Dejé la guía turística en el hotel." },
      { word: "souvenir", example: "Me gustaría comprar un pequeño souvenir." },
      { word: "itinerario", example: "Déjeme revisar mi itinerario de mañana." },
      { word: "lugar emblemático", example: "Esa torre es un lugar emblemático famoso." },
      { word: "indicaciones", example: "¿Puede darme indicaciones al museo?" },
      { word: "equipaje", example: "Mi equipaje es demasiado pesado." },
      { word: "pasaporte", example: "No olvide su pasaporte." },
      { word: "casa de cambio", example: "¿Dónde está la casa de cambio más cercana?" },
      { word: "parada de taxis", example: "La parada de taxis está fuera de la estación." },
      { word: "horario", example: "¿Podría ver el horario del tren?" },
      { word: "turismo", example: "Pasamos el día haciendo turismo." },
      { word: "especialidad local", example: "¿Cuál es la especialidad local aquí?" },
      { word: "objetos perdidos", example: "Necesito ir a objetos perdidos." },
      { word: "calle peatonal", example: "El casco antiguo tiene una bonita calle peatonal." },
      { word: "punto fotográfico", example: "Este es un punto fotográfico popular." },
    ],
    fr: [
      { word: "attraction touristique", example: "Quelle attraction touristique dois-je visiter en premier ?" },
      { word: "carte", example: "Pouvez-vous me montrer sur la carte ?" },
      { word: "métro", example: "Comment puis-je aller à la station de métro ?" },
      { word: "arrêt de bus", example: "Est-ce le bon arrêt de bus pour le centre-ville ?" },
      { word: "billet", example: "Où puis-je acheter un billet ?" },
      { word: "guide touristique", example: "J'ai laissé mon guide touristique à l'hôtel." },
      { word: "souvenir", example: "Je voudrais acheter un petit souvenir." },
      { word: "itinéraire", example: "Laissez-moi vérifier mon itinéraire pour demain." },
      { word: "monument", example: "Cette tour est un monument célèbre." },
      { word: "indications", example: "Pouvez-vous me donner des indications pour le musée ?" },
      { word: "bagages", example: "Mes bagages sont trop lourds." },
      { word: "passeport", example: "N'oubliez pas votre passeport." },
      { word: "bureau de change", example: "Où est le bureau de change le plus proche ?" },
      { word: "station de taxis", example: "La station de taxis est devant la gare." },
      { word: "horaire", example: "Pourrais-je voir l'horaire des trains ?" },
      { word: "visite touristique", example: "Nous avons passé la journée en visite touristique." },
      { word: "spécialité locale", example: "Quelle est la spécialité locale ici ?" },
      { word: "objets trouvés", example: "Je dois aller aux objets trouvés." },
      { word: "rue piétonne", example: "La vieille ville a une jolie rue piétonne." },
      { word: "spot photo", example: "C'est un spot photo populaire." },
    ],
    de: [
      { word: "Sehenswürdigkeit", example: "Welche Sehenswürdigkeit sollte ich zuerst besuchen?" },
      { word: "Karte", example: "Können Sie es mir auf der Karte zeigen?" },
      { word: "U-Bahn", example: "Wie komme ich zur U-Bahn-Station?" },
      { word: "Bushaltestelle", example: "Ist das die richtige Bushaltestelle für die Innenstadt?" },
      { word: "Fahrkarte", example: "Wo kann ich eine Fahrkarte kaufen?" },
      { word: "Reiseführer", example: "Ich habe meinen Reiseführer im Hotel gelassen." },
      { word: "Souvenir", example: "Ich möchte ein kleines Souvenir kaufen." },
      { word: "Reiseplan", example: "Ich schaue kurz meinen Reiseplan für morgen an." },
      { word: "Wahrzeichen", example: "Dieser Turm ist ein bekanntes Wahrzeichen." },
      { word: "Wegbeschreibung", example: "Können Sie mir den Weg zum Museum beschreiben?" },
      { word: "Gepäck", example: "Mein Gepäck ist zu schwer." },
      { word: "Reisepass", example: "Vergessen Sie Ihren Reisepass nicht." },
      { word: "Wechselstube", example: "Wo ist die nächste Wechselstube?" },
      { word: "Taxistand", example: "Der Taxistand ist vor dem Bahnhof." },
      { word: "Fahrplan", example: "Könnte ich den Zugfahrplan sehen?" },
      { word: "Sightseeing", example: "Wir haben den Tag mit Sightseeing verbracht." },
      { word: "lokale Spezialität", example: "Was ist hier die lokale Spezialität?" },
      { word: "Fundbüro", example: "Ich muss zum Fundbüro." },
      { word: "Fußgängerzone", example: "Die Altstadt hat eine schöne Fußgängerzone." },
      { word: "Fotomotiv", example: "Das ist ein beliebtes Fotomotiv." },
    ],
  },
  hotel: {
    en: [
      { word: "check-in", example: "What time is check-in?" },
      { word: "check-out", example: "I'd like to check out, please." },
      { word: "reservation", example: "I have a reservation under Lee." },
      { word: "room key", example: "I lost my room key." },
      { word: "front desk", example: "Please call the front desk." },
      { word: "wake-up call", example: "Could I have a wake-up call at seven?" },
      { word: "room service", example: "I'd like to order room service." },
      { word: "extra towel", example: "Could you bring an extra towel?" },
      { word: "Wi-Fi password", example: "What is the Wi-Fi password?" },
      { word: "single room", example: "Do you have a single room available?" },
      { word: "double room", example: "I'd prefer a double room." },
      { word: "elevator", example: "The elevators are around the corner." },
      { word: "luggage storage", example: "Is there luggage storage after check-out?" },
      { word: "late checkout", example: "Can I request a late checkout?" },
      { word: "minibar", example: "Is the minibar included?" },
      { word: "air conditioning", example: "The air conditioning isn't working." },
      { word: "housekeeping", example: "Please ask housekeeping to clean the room." },
      { word: "concierge", example: "The concierge can book a taxi." },
      { word: "deposit", example: "Do I need to leave a deposit?" },
      { word: "ocean view", example: "Is an ocean view room available?" },
    ],
    zh: [
      { word: "入住", example: "入住时间是几点？" },
      { word: "退房", example: "我想退房。" },
      { word: "预订", example: "我有李姓的预订。" },
      { word: "房卡", example: "我把房卡弄丢了。" },
      { word: "前台", example: "请打电话给前台。" },
      { word: "叫醒服务", example: "可以七点叫醒我吗？" },
      { word: "客房服务", example: "我想点客房服务。" },
      { word: "额外毛巾", example: "能再送一条毛巾吗？" },
      { word: "无线密码", example: "无线网密码是什么？" },
      { word: "单人间", example: "还有单人间吗？" },
      { word: "双人间", example: "我想要双人间。" },
      { word: "电梯", example: "电梯在拐角处。" },
      { word: "行李寄存", example: "退房后可以寄存行李吗？" },
      { word: "延迟退房", example: "可以申请延迟退房吗？" },
      { word: "迷你吧", example: "迷你吧包含在房价里吗？" },
      { word: "空调", example: "空调坏了。" },
      { word: "客房清洁", example: "请让客房清洁打扫房间。" },
      { word: "礼宾", example: "礼宾可以帮我叫出租车。" },
      { word: "押金", example: "需要交押金吗？" },
      { word: "海景房", example: "还有海景房吗？" },
    ],
    ja: [
      { word: "チェックイン", example: "チェックインは何時ですか。" },
      { word: "チェックアウト", example: "チェックアウトをお願いします。" },
      { word: "予約", example: "リーの名前で予約しています。" },
      { word: "部屋の鍵", example: "部屋の鍵をなくしました。" },
      { word: "フロント", example: "フロントに電話してください。" },
      { word: "モーニングコール", example: "七時にモーニングコールをお願いできますか。" },
      { word: "ルームサービス", example: "ルームサービスを注文したいです。" },
      { word: "タオルの追加", example: "タオルを追加で持ってきていただけますか。" },
      { word: "Wi-Fiのパスワード", example: "Wi-Fiのパスワードは何ですか。" },
      { word: "シングルルーム", example: "シングルルームは空いていますか。" },
      { word: "ダブルルーム", example: "ダブルルームがいいです。" },
      { word: "エレベーター", example: "エレベーターは角を曲がったところです。" },
      { word: "荷物預かり", example: "チェックアウト後に荷物預かりはできますか。" },
      { word: "レイトチェックアウト", example: "レイトチェックアウトをお願いできますか。" },
      { word: "ミニバー", example: "ミニバーは料金に含まれていますか。" },
      { word: "エアコン", example: "エアコンが動きません。" },
      { word: "ハウスキーピング", example: "ハウスキーピングに部屋を掃除してもらってください。" },
      { word: "コンシェルジュ", example: "コンシェルジュがタクシーを手配できます。" },
      { word: "デポジット", example: "デポジットは必要ですか。" },
      { word: "オーシャンビュー", example: "オーシャンビューの部屋はありますか。" },
    ],
    es: [
      { word: "registro de entrada", example: "¿A qué hora es el registro de entrada?" },
      { word: "salida", example: "Quisiera hacer la salida, por favor." },
      { word: "reserva", example: "Tengo una reserva a nombre de Lee." },
      { word: "llave de la habitación", example: "Perdí la llave de la habitación." },
      { word: "recepción", example: "Por favor llame a recepción." },
      { word: "llamada despertador", example: "¿Podría pedirme una llamada despertador a las siete?" },
      { word: "servicio de habitación", example: "Quisiera pedir servicio de habitación." },
      { word: "toalla extra", example: "¿Podría traerme una toalla extra?" },
      { word: "contraseña del Wi-Fi", example: "¿Cuál es la contraseña del Wi-Fi?" },
      { word: "habitación individual", example: "¿Tiene una habitación individual disponible?" },
      { word: "habitación doble", example: "Prefiero una habitación doble." },
      { word: "ascensor", example: "Los ascensores están a la vuelta de la esquina." },
      { word: "consigna de equipaje", example: "¿Hay consigna de equipaje después de la salida?" },
      { word: "salida tardía", example: "¿Puedo solicitar una salida tardía?" },
      { word: "minibar", example: "¿El minibar está incluido?" },
      { word: "aire acondicionado", example: "El aire acondicionado no funciona." },
      { word: "limpieza", example: "Por favor pida a limpieza que prepare la habitación." },
      { word: "conserje", example: "El conserje puede pedir un taxi." },
      { word: "depósito", example: "¿Necesito dejar un depósito?" },
      { word: "vista al mar", example: "¿Hay una habitación con vista al mar?" },
    ],
    fr: [
      { word: "enregistrement", example: "À quelle heure est l'enregistrement ?" },
      { word: "départ", example: "Je voudrais régler mon départ, s'il vous plaît." },
      { word: "réservation", example: "J'ai une réservation au nom de Lee." },
      { word: "clé de chambre", example: "J'ai perdu ma clé de chambre." },
      { word: "réception", example: "Veuillez appeler la réception." },
      { word: "réveil téléphonique", example: "Pourrais-je avoir un réveil à sept heures ?" },
      { word: "service en chambre", example: "Je voudrais commander le service en chambre." },
      { word: "serviette supplémentaire", example: "Pourriez-vous apporter une serviette supplémentaire ?" },
      { word: "mot de passe Wi-Fi", example: "Quel est le mot de passe Wi-Fi ?" },
      { word: "chambre simple", example: "Avez-vous une chambre simple disponible ?" },
      { word: "chambre double", example: "Je préférerais une chambre double." },
      { word: "ascenseur", example: "Les ascenseurs sont au coin." },
      { word: "consigne à bagages", example: "Y a-t-il une consigne après le départ ?" },
      { word: "départ tardif", example: "Puis-je demander un départ tardif ?" },
      { word: "minibar", example: "Le minibar est-il inclus ?" },
      { word: "climatisation", example: "La climatisation ne fonctionne pas." },
      { word: "ménage", example: "Veuillez demander au ménage de nettoyer la chambre." },
      { word: "concierge", example: "Le concierge peut réserver un taxi." },
      { word: "caution", example: "Dois-je laisser une caution ?" },
      { word: "vue sur la mer", example: "Y a-t-il une chambre avec vue sur la mer ?" },
    ],
    de: [
      { word: "Check-in", example: "Um wie viel Uhr ist der Check-in?" },
      { word: "Check-out", example: "Ich möchte bitte auschecken." },
      { word: "Reservierung", example: "Ich habe eine Reservierung auf den Namen Lee." },
      { word: "Zimmerschlüssel", example: "Ich habe meinen Zimmerschlüssel verloren." },
      { word: "Rezeption", example: "Bitte rufen Sie die Rezeption an." },
      { word: "Weckruf", example: "Könnte ich um sieben einen Weckruf bekommen?" },
      { word: "Zimmerservice", example: "Ich möchte Zimmerservice bestellen." },
      { word: "zusätzliches Handtuch", example: "Könnten Sie ein zusätzliches Handtuch bringen?" },
      { word: "WLAN-Passwort", example: "Wie lautet das WLAN-Passwort?" },
      { word: "Einzelzimmer", example: "Haben Sie ein Einzelzimmer frei?" },
      { word: "Doppelzimmer", example: "Ich hätte gerne ein Doppelzimmer." },
      { word: "Aufzug", example: "Die Aufzüge sind um die Ecke." },
      { word: "Gepäckaufbewahrung", example: "Gibt es nach dem Check-out eine Gepäckaufbewahrung?" },
      { word: "später Check-out", example: "Kann ich einen späteren Check-out beantragen?" },
      { word: "Minibar", example: "Ist die Minibar inklusive?" },
      { word: "Klimaanlage", example: "Die Klimaanlage funktioniert nicht." },
      { word: "Housekeeping", example: "Bitte lassen Sie das Housekeeping das Zimmer reinigen." },
      { word: "Concierge", example: "Der Concierge kann ein Taxi bestellen." },
      { word: "Kaution", example: "Muss ich eine Kaution hinterlegen?" },
      { word: "Meerblick", example: "Gibt es ein Zimmer mit Meerblick?" },
    ],
  },
  restaurant: {
    en: [
      { word: "menu", example: "Could I see the menu, please?" },
      { word: "reservation", example: "I have a reservation for two." },
      { word: "appetizer", example: "I'd like an appetizer to start." },
      { word: "main course", example: "What do you recommend for the main course?" },
      { word: "dessert", example: "We'll share a dessert." },
      { word: "bill", example: "Could we have the bill, please?" },
      { word: "tip", example: "Is the tip included?" },
      { word: "allergy", example: "I have a peanut allergy." },
      { word: "spicy", example: "Is this dish spicy?" },
      { word: "vegetarian", example: "Do you have vegetarian options?" },
      { word: "table for two", example: "A table for two, please." },
      { word: "water", example: "Could we have some water?" },
      { word: "special of the day", example: "What is the special of the day?" },
      { word: "takeout", example: "I'd like this to go as takeout." },
      { word: "fork", example: "Could I have another fork?" },
      { word: "napkin", example: "May I have a napkin?" },
      { word: "order", example: "Are you ready to order?" },
      { word: "waiter", example: "Excuse me, waiter!" },
      { word: "delicious", example: "This soup is delicious." },
      { word: "split the bill", example: "Can we split the bill?" },
    ],
    zh: [
      { word: "菜单", example: "请给我看一下菜单。" },
      { word: "预订", example: "我预订了两人桌。" },
      { word: "开胃菜", example: "我想先来一份开胃菜。" },
      { word: "主菜", example: "主菜你推荐什么？" },
      { word: "甜点", example: "我们想分享一份甜点。" },
      { word: "账单", example: "请给我们账单。" },
      { word: "小费", example: "小费包含在内吗？" },
      { word: "过敏", example: "我对花生过敏。" },
      { word: "辣", example: "这道菜辣吗？" },
      { word: "素食", example: "有素食选项吗？" },
      { word: "两人桌", example: "请给我两人桌。" },
      { word: "水", example: "能给我们一些水吗？" },
      { word: "今日特餐", example: "今日特餐是什么？" },
      { word: "外带", example: "我想外带这份。" },
      { word: "叉子", example: "能再给我一把叉子吗？" },
      { word: "餐巾", example: "可以给我一张餐巾吗？" },
      { word: "点餐", example: "可以点餐了吗？" },
      { word: "服务员", example: "不好意思，服务员！" },
      { word: "好吃", example: "这汤很好喝。" },
      { word: "分开付账", example: "我们可以分开付账吗？" },
    ],
    ja: [
      { word: "メニュー", example: "メニューを見せていただけますか。" },
      { word: "予約", example: "二人で予約しています。" },
      { word: "前菜", example: "まず前菜をお願いします。" },
      { word: "メイン料理", example: "メイン料理のおすすめは何ですか。" },
      { word: "デザート", example: "デザートをシェアします。" },
      { word: "お会計", example: "お会計をお願いします。" },
      { word: "チップ", example: "チップは含まれていますか。" },
      { word: "アレルギー", example: "ピーナッツアレルギーがあります。" },
      { word: "辛い", example: "この料理は辛いですか。" },
      { word: "ベジタリアン", example: "ベジタリアン向けのメニューはありますか。" },
      { word: "二人席", example: "二人席をお願いします。" },
      { word: "水", example: "お水をいただけますか。" },
      { word: "本日のおすすめ", example: "本日のおすすめは何ですか。" },
      { word: "持ち帰り", example: "これを持ち帰りにしたいです。" },
      { word: "フォーク", example: "フォークをもう一本いただけますか。" },
      { word: "ナプキン", example: "ナプキンをいただけますか。" },
      { word: "注文する", example: "ご注文はお決まりですか。" },
      { word: "店員", example: "すみません、店員さん！" },
      { word: "おいしい", example: "このスープはおいしいです。" },
      { word: "割り勘", example: "割り勘にできますか。" },
    ],
    es: [
      { word: "menú", example: "¿Me puede traer el menú, por favor?" },
      { word: "reserva", example: "Tengo una reserva para dos." },
      { word: "entrada", example: "Quisiera una entrada para empezar." },
      { word: "plato principal", example: "¿Qué recomienda como plato principal?" },
      { word: "postre", example: "Vamos a compartir un postre." },
      { word: "cuenta", example: "¿Nos trae la cuenta, por favor?" },
      { word: "propina", example: "¿La propina está incluida?" },
      { word: "alergia", example: "Tengo alergia al maní." },
      { word: "picante", example: "¿Este plato es picante?" },
      { word: "vegetariano", example: "¿Tienen opciones vegetarianas?" },
      { word: "mesa para dos", example: "Una mesa para dos, por favor." },
      { word: "agua", example: "¿Nos puede traer agua?" },
      { word: "especial del día", example: "¿Cuál es el especial del día?" },
      { word: "para llevar", example: "Quisiera esto para llevar." },
      { word: "tenedor", example: "¿Me puede traer otro tenedor?" },
      { word: "servilleta", example: "¿Me da una servilleta?" },
      { word: "pedir", example: "¿Están listos para pedir?" },
      { word: "camarero", example: "¡Disculpe, camarero!" },
      { word: "delicioso", example: "Esta sopa está deliciosa." },
      { word: "dividir la cuenta", example: "¿Podemos dividir la cuenta?" },
    ],
    fr: [
      { word: "carte", example: "Pourrais-je voir la carte, s'il vous plaît ?" },
      { word: "réservation", example: "J'ai une réservation pour deux." },
      { word: "entrée", example: "Je voudrais une entrée pour commencer." },
      { word: "plat principal", example: "Que recommandez-vous comme plat principal ?" },
      { word: "dessert", example: "Nous allons partager un dessert." },
      { word: "addition", example: "Pourrions-nous avoir l'addition, s'il vous plaît ?" },
      { word: "pourboire", example: "Le pourboire est-il inclus ?" },
      { word: "allergie", example: "J'ai une allergie aux arachides." },
      { word: "épicé", example: "Ce plat est-il épicé ?" },
      { word: "végétarien", example: "Avez-vous des options végétariennes ?" },
      { word: "table pour deux", example: "Une table pour deux, s'il vous plaît." },
      { word: "eau", example: "Pourrions-nous avoir de l'eau ?" },
      { word: "plat du jour", example: "Quel est le plat du jour ?" },
      { word: "à emporter", example: "Je voudrais ceci à emporter." },
      { word: "fourchette", example: "Pourrais-je avoir une autre fourchette ?" },
      { word: "serviette", example: "Puis-je avoir une serviette ?" },
      { word: "commander", example: "Êtes-vous prêts à commander ?" },
      { word: "serveur", example: "Excusez-moi, serveur !" },
      { word: "délicieux", example: "Cette soupe est délicieuse." },
      { word: "partager l'addition", example: "Pouvons-nous partager l'addition ?" },
    ],
    de: [
      { word: "Speisekarte", example: "Könnte ich bitte die Speisekarte sehen?" },
      { word: "Reservierung", example: "Ich habe eine Reservierung für zwei." },
      { word: "Vorspeise", example: "Ich hätte gerne eine Vorspeise zum Start." },
      { word: "Hauptgericht", example: "Was empfehlen Sie als Hauptgericht?" },
      { word: "Nachtisch", example: "Wir teilen uns einen Nachtisch." },
      { word: "Rechnung", example: "Könnten wir bitte die Rechnung haben?" },
      { word: "Trinkgeld", example: "Ist das Trinkgeld inklusive?" },
      { word: "Allergie", example: "Ich habe eine Erdnussallergie." },
      { word: "scharf", example: "Ist dieses Gericht scharf?" },
      { word: "vegetarisch", example: "Haben Sie vegetarische Optionen?" },
      { word: "Tisch für zwei", example: "Einen Tisch für zwei, bitte." },
      { word: "Wasser", example: "Könnten wir etwas Wasser bekommen?" },
      { word: "Tagesgericht", example: "Was ist das Tagesgericht?" },
      { word: "zum Mitnehmen", example: "Ich hätte das gerne zum Mitnehmen." },
      { word: "Gabel", example: "Könnte ich bitte noch eine Gabel haben?" },
      { word: "Serviette", example: "Darf ich eine Serviette haben?" },
      { word: "bestellen", example: "Sind Sie bereit zu bestellen?" },
      { word: "Kellner", example: "Entschuldigung, Kellner!" },
      { word: "lecker", example: "Diese Suppe ist lecker." },
      { word: "getrennt zahlen", example: "Können wir getrennt zahlen?" },
    ],
  },
  airport: {
    en: [
      { word: "boarding pass", example: "Please show your boarding pass." },
      { word: "check-in counter", example: "Where is the check-in counter?" },
      { word: "security check", example: "We need to go through security check." },
      { word: "gate", example: "Which gate is for flight 208?" },
      { word: "boarding", example: "Boarding starts in twenty minutes." },
      { word: "passport control", example: "Follow the signs to passport control." },
      { word: "customs", example: "Do I need to declare this at customs?" },
      { word: "baggage claim", example: "Baggage claim is downstairs." },
      { word: "carry-on", example: "Is this bag allowed as carry-on?" },
      { word: "overweight", example: "Your suitcase is overweight." },
      { word: "flight delay", example: "There is a flight delay of one hour." },
      { word: "departure", example: "What is the departure time?" },
      { word: "arrival", example: "My arrival is after midnight." },
      { word: "terminal", example: "Which terminal should I go to?" },
      { word: "seat assignment", example: "Can I change my seat assignment?" },
      { word: "window seat", example: "I'd like a window seat, please." },
      { word: "aisle seat", example: "Do you have an aisle seat left?" },
      { word: "connecting flight", example: "Where is my connecting flight?" },
      { word: "priority boarding", example: "Priority boarding is for first class." },
      { word: "lost luggage", example: "I need to report lost luggage." },
    ],
    zh: [
      { word: "登机牌", example: "请出示登机牌。" },
      { word: "值机柜台", example: "值机柜台在哪里？" },
      { word: "安检", example: "我们需要过安检。" },
      { word: "登机口", example: "208 航班在哪个登机口？" },
      { word: "登机", example: "二十分钟后开始登机。" },
      { word: "护照检查", example: "请跟着指示牌去护照检查处。" },
      { word: "海关", example: "这个需要在海关申报吗？" },
      { word: "行李提取", example: "行李提取在楼下。" },
      { word: "随身行李", example: "这个包可以当随身行李吗？" },
      { word: "超重", example: "您的行李箱超重了。" },
      { word: "航班延误", example: "航班延误一小时。" },
      { word: "起飞", example: "起飞时间是几点？" },
      { word: "到达", example: "我午夜后到达。" },
      { word: "航站楼", example: "我该去哪个航站楼？" },
      { word: "座位分配", example: "可以更改座位分配吗？" },
      { word: "靠窗座位", example: "我想要靠窗座位。" },
      { word: "靠过道座位", example: "还有靠过道的座位吗？" },
      { word: "转机航班", example: "我的转机航班在哪里？" },
      { word: "优先登机", example: "优先登机给头等舱旅客。" },
      { word: "行李丢失", example: "我需要申报行李丢失。" },
    ],
    ja: [
      { word: "搭乗券", example: "搭乗券を見せてください。" },
      { word: "チェックインカウンター", example: "チェックインカウンターはどこですか。" },
      { word: "保安検査", example: "保安検査を通る必要があります。" },
      { word: "ゲート", example: "便名208のゲートはどれですか。" },
      { word: "搭乗", example: "搭乗は二十分後に始まります。" },
      { word: "出入国審査", example: "標識に従って出入国審査へ進んでください。" },
      { word: "税関", example: "これは税関で申告が必要ですか。" },
      { word: "手荷物受取", example: "手荷物受取は地下です。" },
      { word: "機内持ち込み", example: "このバッグは機内持ち込みできますか。" },
      { word: "重量超過", example: "スーツケースが重量超過です。" },
      { word: "欠航遅延", example: "フライトが一時間遅延しています。" },
      { word: "出発", example: "出発時刻は何時ですか。" },
      { word: "到着", example: "到着は深夜過ぎです。" },
      { word: "ターミナル", example: "どのターミナルに行けばいいですか。" },
      { word: "座席指定", example: "座席指定を変更できますか。" },
      { word: "窓側座席", example: "窓側座席をお願いします。" },
      { word: "通路側座席", example: "通路側座席は残っていますか。" },
      { word: "乗り継ぎ便", example: "乗り継ぎ便はどこですか。" },
      { word: "優先搭乗", example: "優先搭乗はファーストクラス向けです。" },
      { word: "荷物紛失", example: "荷物紛失を届け出る必要があります。" },
    ],
    es: [
      { word: "tarjeta de embarque", example: "Por favor muestre su tarjeta de embarque." },
      { word: "mostrador de facturación", example: "¿Dónde está el mostrador de facturación?" },
      { word: "control de seguridad", example: "Tenemos que pasar el control de seguridad." },
      { word: "puerta de embarque", example: "¿Qué puerta es para el vuelo 208?" },
      { word: "embarque", example: "El embarque comienza en veinte minutos." },
      { word: "control de pasaportes", example: "Siga las señales al control de pasaportes." },
      { word: "aduana", example: "¿Debo declarar esto en la aduana?" },
      { word: "recogida de equipaje", example: "La recogida de equipaje está abajo." },
      { word: "equipaje de mano", example: "¿Se permite esta bolsa como equipaje de mano?" },
      { word: "exceso de peso", example: "Su maleta tiene exceso de peso." },
      { word: "retraso del vuelo", example: "Hay un retraso del vuelo de una hora." },
      { word: "salida", example: "¿Cuál es la hora de salida?" },
      { word: "llegada", example: "Mi llegada es después de medianoche." },
      { word: "terminal", example: "¿A qué terminal debo ir?" },
      { word: "asignación de asiento", example: "¿Puedo cambiar mi asignación de asiento?" },
      { word: "asiento de ventana", example: "Quisiera un asiento de ventana, por favor." },
      { word: "asiento de pasillo", example: "¿Queda algún asiento de pasillo?" },
      { word: "vuelo de conexión", example: "¿Dónde está mi vuelo de conexión?" },
      { word: "embarque prioritario", example: "El embarque prioritario es para primera clase." },
      { word: "equipaje perdido", example: "Necesito reportar equipaje perdido." },
    ],
    fr: [
      { word: "carte d'embarquement", example: "Veuillez montrer votre carte d'embarquement." },
      { word: "comptoir d'enregistrement", example: "Où est le comptoir d'enregistrement ?" },
      { word: "contrôle de sécurité", example: "Nous devons passer le contrôle de sécurité." },
      { word: "porte d'embarquement", example: "Quelle porte est pour le vol 208 ?" },
      { word: "embarquement", example: "L'embarquement commence dans vingt minutes." },
      { word: "contrôle des passeports", example: "Suivez les panneaux vers le contrôle des passeports." },
      { word: "douane", example: "Dois-je déclarer ceci à la douane ?" },
      { word: "retrait des bagages", example: "Le retrait des bagages est en bas." },
      { word: "bagage cabine", example: "Ce sac est-il autorisé en bagage cabine ?" },
      { word: "excédent de poids", example: "Votre valise a un excédent de poids." },
      { word: "retard de vol", example: "Il y a un retard de vol d'une heure." },
      { word: "départ", example: "Quelle est l'heure de départ ?" },
      { word: "arrivée", example: "Mon arrivée est après minuit." },
      { word: "terminal", example: "Vers quel terminal dois-je aller ?" },
      { word: "attribution de siège", example: "Puis-je changer mon attribution de siège ?" },
      { word: "siège côté fenêtre", example: "Je voudrais un siège côté fenêtre, s'il vous plaît." },
      { word: "siège côté couloir", example: "Reste-t-il un siège côté couloir ?" },
      { word: "vol de correspondance", example: "Où est mon vol de correspondance ?" },
      { word: "embarquement prioritaire", example: "L'embarquement prioritaire est pour la première classe." },
      { word: "bagages perdus", example: "Je dois signaler des bagages perdus." },
    ],
    de: [
      { word: "Bordkarte", example: "Bitte zeigen Sie Ihre Bordkarte." },
      { word: "Check-in-Schalter", example: "Wo ist der Check-in-Schalter?" },
      { word: "Sicherheitskontrolle", example: "Wir müssen durch die Sicherheitskontrolle." },
      { word: "Flugsteig", example: "Welcher Flugsteig ist für Flug 208?" },
      { word: "Boarding", example: "Das Boarding beginnt in zwanzig Minuten." },
      { word: "Passkontrolle", example: "Folgen Sie den Schildern zur Passkontrolle." },
      { word: "Zoll", example: "Muss ich das beim Zoll anmelden?" },
      { word: "Gepäckausgabe", example: "Die Gepäckausgabe ist unten." },
      { word: "Handgepäck", example: "Ist diese Tasche als Handgepäck erlaubt?" },
      { word: "Übergewicht", example: "Ihr Koffer hat Übergewicht." },
      { word: "Flugverspätung", example: "Es gibt eine Flugverspätung von einer Stunde." },
      { word: "Abflug", example: "Wann ist die Abflugzeit?" },
      { word: "Ankunft", example: "Meine Ankunft ist nach Mitternacht." },
      { word: "Terminal", example: "Zu welchem Terminal soll ich gehen?" },
      { word: "Sitzplatzzuweisung", example: "Kann ich meine Sitzplatzzuweisung ändern?" },
      { word: "Fensterplatz", example: "Ich hätte gerne einen Fensterplatz." },
      { word: "Gangplatz", example: "Haben Sie noch einen Gangplatz?" },
      { word: "Anschlussflug", example: "Wo ist mein Anschlussflug?" },
      { word: "Priority Boarding", example: "Priority Boarding ist für die First Class." },
      { word: "verlorenes Gepäck", example: "Ich muss verlorenes Gepäck melden." },
    ],
  },
};

// Fix accidental space in " Pedestrian street"
VOCAB_BY_CATEGORY.travel.en[18] = {
  word: "pedestrian street",
  example: "The old town has a nice pedestrian street.",
};

async function pickDefaultVoiceRoleId(
  db: AppPrismaClient,
  languageId: string,
): Promise<string | null> {
  const role = await db.voiceRole.findFirst({
    where: { languageId, status: "active" },
    orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }],
    select: { id: true },
  });
  return role?.id ?? null;
}

export async function ensureReadAloudContentSeed(db: AppPrismaClient): Promise<void> {
  const langRows = await db.language.findMany({
    where: { code: { in: ["en", "zh", "ja", "es", "fr", "de"] } },
    select: { id: true, code: true },
  });
  const langByCode = Object.fromEntries(langRows.map((l) => [l.code, l]));

  for (const cat of CATEGORIES) {
    let category = await db.readAloudCategory.findUnique({ where: { code: cat.code } });
    if (!category) {
      category = await db.readAloudCategory.create({
        data: {
          code: cat.code,
          name: cat.name,
          nameEn: cat.nameEn,
          icon: cat.icon,
          description: cat.description,
          descriptionEn: cat.descriptionEn,
          sortOrder: cat.sortOrder,
          status: "active",
          remark: READ_ALOUD_SEED_TAG,
        },
      });
      console.info(`[data-seed] read-aloud category ${cat.code}`);
    } else if (category.remark !== READ_ALOUD_SEED_TAG) {
      await db.readAloudCategory.update({
        where: { id: category.id },
        data: {
          name: cat.name,
          nameEn: cat.nameEn,
          icon: cat.icon,
          description: cat.description,
          descriptionEn: cat.descriptionEn,
          sortOrder: cat.sortOrder,
          status: "active",
          remark: READ_ALOUD_SEED_TAG,
        },
      });
    }

    for (const [langCode, locale] of Object.entries(cat.locales)) {
      const lang = langByCode[langCode];
      if (!lang) continue;
      const existingLocale = await db.readAloudCategoryLocale.findUnique({
        where: {
          categoryId_languageId: { categoryId: category.id, languageId: lang.id },
        },
      });
      if (existingLocale) {
        if (existingLocale.name !== locale.name || existingLocale.description !== locale.description) {
          await db.readAloudCategoryLocale.update({
            where: { id: existingLocale.id },
            data: { name: locale.name, description: locale.description },
          });
        }
        continue;
      }
      await db.readAloudCategoryLocale.create({
        data: {
          categoryId: category.id,
          languageId: lang.id,
          name: locale.name,
          description: locale.description,
        },
      });
    }

    const vocabByLang = VOCAB_BY_CATEGORY[cat.code];
    if (!vocabByLang) continue;

    for (const [langCode, items] of Object.entries(vocabByLang)) {
      const lang = langByCode[langCode];
      if (!lang) continue;
      const voiceRoleId = await pickDefaultVoiceRoleId(db, lang.id);
      if (!voiceRoleId) {
        console.warn(`[data-seed] skip vocab ${cat.code}/${langCode}: no voice role`);
        continue;
      }

      const existingCount = await db.readAloudVocabulary.count({
        where: {
          categoryId: category.id,
          languageId: lang.id,
          status: "active",
          remark: READ_ALOUD_SEED_TAG,
        },
      });
      if (existingCount >= items.length) continue;

      // 若已有部分种子词，按 word 去重补齐
      const existingWords = new Set(
        (
          await db.readAloudVocabulary.findMany({
            where: { categoryId: category.id, languageId: lang.id },
            select: { word: true },
          })
        ).map((v) => v.word),
      );

      let sortOrder = existingCount;
      for (const item of items) {
        if (existingWords.has(item.word)) continue;
        sortOrder += 1;
        await db.readAloudVocabulary.create({
          data: {
            categoryId: category.id,
            languageId: lang.id,
            word: item.word,
            exampleSentence: item.example,
            voiceRoleId,
            sortOrder,
            status: "active",
            remark: READ_ALOUD_SEED_TAG,
          },
        });
      }
      console.info(`[data-seed] read-aloud vocab ${cat.code}/${langCode} (+up to ${items.length})`);
    }
  }
}
